### ISSUE TITLE
Error when using bootstrap-decorator.js

### ISSUE THREAD

**Issue by slyadams** [json-schema-form/angular-schema-form-bootstrap#26]
When using the `bootstrap-decorator.js` from this repository instead of the `dist/bootstrap-decorator.js` direct from ASF I get the following error:

```
angular.js:13708 TypeError: Cannot read property 'reduce' of undefined
    at build (http://127.0.0.1:8080/bower_components/angular-schema-form/dist/schema-form.js:261:12)
    at Object.build (http://127.0.0.1:8080/bower_components/angular-schema-form/dist/schema-form.js:309:22)
    at simpleTransclusion (http://127.0.0.1:8080/bower_components/angular-schema-form/dist/schema-form.js:144:27)
    at http://127.0.0.1:8080/bower_components/angular-schema-form/dist/schema-form.js:321:46
    at Array.forEach (native)
    at http://127.0.0.1:8080/bower_components/angular-schema-form/dist/schema-form.js:321:23
    at Array.reduce (native)
    at build (http://127.0.0.1:8080/bower_components/angular-schema-form/dist/schema-form.js:261:13)
    at Object.build (http://127.0.0.1:8080/bower_components/angular-schema-form/dist/schema-form.js:309:22)
    at simpleTransclusion (http://127.0.0.1:8080/bower_components/angular-schema-form/dist/schema-form.js:144:27)
```

Note: this also happens if I re-build.

**Comment by rowino** [comment]
I've had this issue before what I usually do is recreate my own decorator from the one included in the main repo. Not sure what causes it though and mostly assume disparity in versions :( Anyway, quick solution, update the one in the main repo. I hope someone else has a better solution

**Comment by slyadams** [comment]
I suspect you're right and its a version issue, the ASF version I got from bower but the bootstrap decorator got from gihub. I figured if worse comes to worse I could do that, just means manually extracting all the templates etc. No big deal, just a pain.

**Comment by slyadams** [comment]
I got the latest devel angular-schema-form and angular-schema-form-bootstrap from github, built them both and it doesn't work. Perhaps there's a specific branch I should use, but it makes it very hard to write addons when examples show using things like sfNewArray.

**Comment by slyadams** [comment]
Finally got to the bottom of this, I had a form def like:

```
{
    "type": "section",
    "condition": "model.unlimit"
}
```

With no 'items' entry.

**Comment by Anthropic** [comment]
Sorry @slyadams I could have answered this, but only found time now and you already beat me to it, glad you resolved it. Feel free to nag me in gitter, I don't take offense at nagging and I can get busy enough that it becomes hard to switch off work mode even after hours, so it is actually good to be reminded that work has finished for the day and it is time for fun work! :)

**Comment by slyadams** [comment]
No worries!
