### ISSUE TITLE
Feature: Default Select placeholder.

### ISSUE THREAD

**Issue by eiwi1101** [json-schema-form/angular-schema-form-bootstrap#27]
There may be a method to do this, I cannot find it. Currently required Select fields are not visually flagged as required, so I would like to implement a placeholder option that is not blank, with some "select one" message, to indicate that this select field is required.

**Comment by Anthropic** [comment]
@eiwi1101 this is done by ensuring the first option has a valid value but, conveniently, not a blank one!
Form:

``` javascript
"titleMap": [
  {"name":"Please Select", "value":"-"},
  {"name":"a", "value":"a"},
  {"name":"b", "value":"b"},
  {"name":"c", "value":"c"}  
]
```

Schema:

``` javascript
"enum":["-","a","b","c"]
```

Please re-open if you do not feel the question has been answered sufficiently.
