### ISSUE TITLE
Fix release tag for 0.2.0

### ISSUE THREAD

**Issue by chargrove** [json-schema-form/angular-schema-form-bootstrap#38]
The 0.2.0 release does not appear the same as the others and I was unsure if it was an actual release, testing tag, or something else.  To make 0.2.0 appear as a normal release, it should be tagged using an annotated tag instead of a lightweight tag.

Something like the below should do the trick:
```
git checkout 0.2.0
git push --delete origin 0.2.0
git tag -a 0.2.0 -m "New annotated tag for release"
git push --tags
```

@davidlgj 
@json-schema-form/angular-schema-form-bootstrap-lead

**Comment by Anthropic** [comment]
@chargrove thanks, I published it, it had the tag added in git directly and was then published to NPM, it needs to be published via Github publish to look like the other major releases, I did this now :)

I had already started a draft for the 1.0.0 alpha so it will be published correctly soon once I iron out a few more issues.
