### ISSUE TITLE
[Proposal] Hideable array elements

### ISSUE THREAD

**Issue by GerardSoleCa** [json-schema-form/angular-schema-form-bootstrap#4]
Hi, I'm using lots of arrays, and many of them have lots of elements, so I end up with long forms.

I've been searching ways to collapse elements, or at least hide them. Until now, I've reached a simple solution (which deserves some work around), but I think thats in some way functional.

**src/array.html**

```
...
<li class="list-group-item {{form.fieldHtmlClass}}"
        sf-field-model="ng-repeat"
        ng-repeat="item in $$value$$ track by $index">
      <button ng-hide="form.readonly || form.remove === null"
              ng-click="deleteFromArray($index)"
              ng-disabled="form.schema.minItems >= modelArray.length"
              style="position: relative; z-index: 20;"
              type="button" class="close pull-right">
              <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
      </button>
      <button
              ng-click="($parent.show==$index)?$parent.show=-1:$parent.show=$index"
              style="position: relative; z-index: 20; margin-right:10px"
              type="button" class="close pull-right">
              <span aria-hidden="true">{{($parent.show==$index)?'-':'+'}}</span><span class="sr-only">Show</span>
      </button>
      <div schema-form-array-items ng-class="$parent.show=={{$index}}?'':'hidden' "></div>
      <span ng-class="$parent.show=={{$index}}?'hidden':''">{{$index}} - {{form.title}}</span>
    </li>
...
```

**Result**
![optimised](https://cloud.githubusercontent.com/assets/2593956/9465921/03741a88-4b31-11e5-9e39-d711d1e290cf.gif)

**Comment by GerardSoleCa** [comment]
In order to test, this is the right fork and branch :) https://github.com/GerardSoleCa/angular-schema-form-bootstrap/tree/feature-array-collapse-elements

**Comment by AlexAlbala** [comment]
Awesome, I really need this !! Will this feature be available ?

Thank you

**Comment by slyadams** [comment]
+1 for this, we make heavy use of child forms for which we currently use fieldset, this seems like a really nice compact alternative.
