### ISSUE TITLE
Bower Main Section Possibly Incorrect

### ISSUE THREAD

**Issue by mark007** [json-schema-form/angular-schema-form-bootstrap#40]
####  Enhancement
As a user/developer, when I ... I should be able to run a bower install using my bower.json, mentioning the latest commit id, eg "angular-schema-form-bootstrap": "af4eb637c83b3f4fe448afc836e7e2851aa58770"

####  Expected behaviour
I expected when I run a gulp task to wire the dependencies, the file thats documented to be included, ie angular-schema-form-bootstrap-bundled.min.js, to be wired up for me

####  Actual behaviour
It actually wires up only angular-schema-form/dist/angular-schema-form.min.js

####  Related issues
My team is just finding it very hard to understand what we should have in our bower.json, to be able to use the absolute latest alphas of angular-schema-form bootstrap, so that we can make sue of things like support for $ref, but also have our dependencies wired up for us in our project.

I can make a pull request, pointing to the embedded file as the "main" section in the bower.json for angular-schema-form-bootstrap, but I'm not sure if this is the planned solution / final goal of the project.

**Comment by Anthropic** [comment]
@mark007 Bower is a tough one, some people want to keep ASF and ASFB separate and some prefer the bundle, hard to know which to include in bower, I prefer to use NPM and then webpack the code I want, I haven't really enjoyed using bower. Anyway I digress, bower is working for the latest ASF, but I haven't released the alpha for ASFB yet, that is coming, I have just had some family emergencies in the last few weeks which delayed my progress on it. I will try to get to it soon, but until then the alpha really is better off outside of bower, I had planned to sort out bower more for the beta.

I am glad to hear you want to try the updated version, look forward to feedback and issues based on it :)

**Comment by mark007** [comment]
Thanks for the reply Anthropic.

Until the bower side of things is finalized, what we have done is override the main for asf and asfb in our own bower, to include just the bundled.min.js from asfb and nothing from asf.

    "angular-schema-form": {
      "main": []
    },
    "angular-schema-form-bootstrap": {
      "main": [
        "dist/angular-schema-form-bootstrap-bundled.min.js"
      ]
    }

**Comment by Anthropic** [comment]
Glad you have a workaround, this should be working now. Either way I am probably going to drop bower support in future given bower.io website now actively recommends using yarn and webpack instead. Not sure when, but I would suggest you consider migrating at some point, webpack is awesome :)
